name: Deploy Development

on:
  push:
    branches: ["development"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_CAPUB: ${{ vars.VITE_CAPUB }}
          VITE_AD_FREQUENCY_MOBILE: ${{ vars.VITE_AD_FREQUENCY_MOBILE }}
          VITE_AD_FREQUENCY_DESKTOP: ${{ vars.VITE_AD_FREQUENCY_DESKTOP }}
          VITE_BANNER_AD_SLOT: ${{ vars.VITE_BANNER_AD_SLOT }}
          VITE_GRID_AD_SLOT: ${{ vars.VITE_GRID_AD_SLOT }}
          VITE_AD_ID: ${{ vars.VITE_AD_ID }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"

  deploy:
    needs: build
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
